### ISSUE TITLE
Found some mods the tool doesn't seem to work with [1.17.1]

### ISSUE THREAD

**Issue by elhertz** [bloxgate/dynmap-fabric-renderdata#1]
[BetterEnd](https://www.curseforge.com/minecraft/mc-mods/betterend/files/3421221) (works after fixing `fabric.mod.json`)
```
> python simple-texture-generator.py better-end-0.11.0-pre.jar
Traceback (most recent call last):
  File "C:\Users\pc\Desktop\dynmap-fabric-renderdata-master\simple-texture-generator.py", line 22, in <module>
    modData = json.loads(modjar.read("fabric.mod.json"))
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 7 column 129 (char 221)
```

[Architect's Pallete](https://www.curseforge.com/minecraft/mc-mods/architects-palette-fabric/files/3358890) **-** [Draylar's Battle Towers](https://www.curseforge.com/minecraft/mc-mods/draylars-battle-towers/files/3486407) **-** [slotlink](https://www.curseforge.com/minecraft/mc-mods/slotlink/files/3486589)
```
> python simple-texture-generator.py [MOD FILE].jar
Traceback (most recent call last):
  File "C:\Users\pc\Desktop\dynmap-fabric-renderdata-master\simple-texture-generator.py", line 40, in <module>
    entries.append(handler.handle(blockFile, model, modID))
  File "C:\Users\pc\Desktop\dynmap-fabric-renderdata-master\blockhandlers\CubeAllHandler.py", line 13, in handle
    lookupKey = self.determine_namespace_and_adjust_for_lookup(blockModel['textures']['all'])
KeyError: 'all'
```

[Go Fish](https://www.curseforge.com/minecraft/mc-mods/go-fish/files/3452653) **-** [Upgraded Shulkers](https://www.curseforge.com/minecraft/mc-mods/upgraded-shulkers/files/3487599)
```
> python simple-texture-generator.py [MOD FILE].jar
Traceback (most recent call last):
  File "C:\Users\pc\Desktop\dynmap-fabric-renderdata-master\simple-texture-generator.py", line 32, in <module>
    for blockFile in os.listdir(os.path.join(tmpDir.name, "assets", modID, "models", "block")):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\pc\\AppData\\Local\\Temp\\tmpl7y3t82w\\assets\\*[mod name here]*\\models\\block'
```

**Comment by elhertz** [comment]
[Automated Crafting](https://www.curseforge.com/minecraft/mc-mods/automated-crafting/files/3383133) **-** [Dragon Loot](https://www.curseforge.com/minecraft/mc-mods/dragonloot/files/3437929) **-** [Expanded Storage](https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/3475719) **-** [Modern Glass Doors](https://www.curseforge.com/minecraft/mc-mods/modern-glass-doors/files/3351082) **-** [The Graveyard](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-fabric/files/3457664) **-** [Better Hoppers (Hopper+)](https://www.curseforge.com/minecraft/mc-mods/hopper/files/3429289) **-** [Illegal Substances](https://www.curseforge.com/minecraft/mc-mods/illegal-substances-that-you-should-not-do-in-real-life-craft/files/3346181) 👀 **-** [More Respawn Anchors](https://www.curseforge.com/minecraft/mc-mods/more-respawn-anchors) **-** [Stockpile](https://www.curseforge.com/minecraft/mc-mods/stockpile/files/3476863) **-** [Upgraded Ender Chests](https://www.curseforge.com/minecraft/mc-mods/upgraded-ender-chests/files/3393277)
No errors, but the `-texture.txt` file is empty apart from the `modname:[mod name here]` line

[Conjuring](https://www.curseforge.com/minecraft/mc-mods/conjuring/files/3490285) **-** [Decorative](https://www.curseforge.com/minecraft/mc-mods/decorative/files/3345338) **-** [Red Bits](https://www.curseforge.com/minecraft/mc-mods/red-bits/files/3481458) **-** [SlimeologyMC](https://www.curseforge.com/minecraft/mc-mods/slimeologymc/files/3378868) **-** [Trap Expansion](https://www.curseforge.com/minecraft/mc-mods/trap-expansion-fabric/files/3482013)
 There are some missing block textures in the `-texture.txt` file

**Comment by bloxgate** [comment]
> 
> 
> [BetterEnd](https://www.curseforge.com/minecraft/mc-mods/betterend/files/3421221) (works after fixing `fabric.mod.json`)
> 
> ```
> > python simple-texture-generator.py better-end-0.11.0-pre.jar
> Traceback (most recent call last):
>   File "C:\Users\pc\Desktop\dynmap-fabric-renderdata-master\simple-texture-generator.py", line 22, in <module>
>     modData = json.loads(modjar.read("fabric.mod.json"))
>   File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
>     obj, end = self.scan_once(s, idx)
> json.decoder.JSONDecodeError: Invalid control character at: line 7 column 129 (char 221)
> ```
Indeed, it does look like the script isn't happy with the new line in the JSON file. I'll look into it, but a good solution for now would be to just PR the texture file you got generated so future people don't have to generate their own.
> 
> [Architect's Pallete](https://www.curseforge.com/minecraft/mc-mods/architects-palette-fabric/files/3358890) **-** [Draylar's Battle Towers](https://www.curseforge.com/minecraft/mc-mods/draylars-battle-towers/files/3486407) **-** [slotlink](https://www.curseforge.com/minecraft/mc-mods/slotlink/files/3486589)
> 
> ```
> > python simple-texture-generator.py [MOD FILE].jar
> Traceback (most recent call last):
>   File "C:\Users\pc\Desktop\dynmap-fabric-renderdata-master\simple-texture-generator.py", line 40, in <module>
>     entries.append(handler.handle(blockFile, model, modID))
>   File "C:\Users\pc\Desktop\dynmap-fabric-renderdata-master\blockhandlers\CubeAllHandler.py", line 13, in handle
>     lookupKey = self.determine_namespace_and_adjust_for_lookup(blockModel['textures']['all'])
> KeyError: 'all'
> ```
Working on a fix at the moment, I'll update this issue when that's up.

> 
> [Go Fish](https://www.curseforge.com/minecraft/mc-mods/go-fish/files/3452653) **-** [Upgraded Shulkers](https://www.curseforge.com/minecraft/mc-mods/upgraded-shulkers/files/3487599)
> 
> ```
> > python simple-texture-generator.py [MOD FILE].jar
> Traceback (most recent call last):
>   File "C:\Users\pc\Desktop\dynmap-fabric-renderdata-master\simple-texture-generator.py", line 32, in <module>
>     for blockFile in os.listdir(os.path.join(tmpDir.name, "assets", modID, "models", "block")):
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\pc\\AppData\\Local\\Temp\\tmpl7y3t82w\\assets\\*[mod name here]*\\models\\block'
> ```
It seems that these two are storing their assets under a different folder than their mod ID. I don't see an easy way to detect that. I will admit most of my experience is with Forge though, so if someone knows an easy way to determine the actual asset path I'm open to suggestions.


>  
> [Automated Crafting](https://www.curseforge.com/minecraft/mc-mods/automated-crafting/files/3383133) **-** [Dragon Loot](https://www.curseforge.com/minecraft/mc-mods/dragonloot/files/3437929) **-** [Expanded Storage](https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/3475719) **-** [Modern Glass Doors](https://www.curseforge.com/minecraft/mc-mods/modern-glass-doors/files/3351082) **-** [The Graveyard](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-fabric/files/3457664) **-** [Better Hoppers (Hopper+)](https://www.curseforge.com/minecraft/mc-mods/hopper/files/3429289) **-** [Illegal Substances](https://www.curseforge.com/minecraft/mc-mods/illegal-substances-that-you-should-not-do-in-real-life-craft/files/3346181) 👀 **-** [More Respawn Anchors](https://www.curseforge.com/minecraft/mc-mods/more-respawn-anchors) **-** [Stockpile](https://www.curseforge.com/minecraft/mc-mods/stockpile/files/3476863) **-** [Upgraded Ender Chests](https://www.curseforge.com/minecraft/mc-mods/upgraded-ender-chests/files/3393277) No errors, but the `-texture.txt` file is empty apart from the `modname:[mod name here]` line
> 
> [Conjuring](https://www.curseforge.com/minecraft/mc-mods/conjuring/files/3490285) **-** [Decorative](https://www.curseforge.com/minecraft/mc-mods/decorative/files/3345338) **-** [Red Bits](https://www.curseforge.com/minecraft/mc-mods/red-bits/files/3481458) **-** [SlimeologyMC](https://www.curseforge.com/minecraft/mc-mods/slimeologymc/files/3378868) **-** [Trap Expansion](https://www.curseforge.com/minecraft/mc-mods/trap-expansion-fabric/files/3482013) There are some missing block textures in the `-texture.txt` file

From a quick look, it looks like these mods add a lot of blocks that aren't simple cubes. The script only really supports blocks that don't need model definitions. There's a slightly outdated list of what types are supported in README.md. I do plan on adding support for some non-simple blocks that have renderers, such as chests, in the future but for now the `-texture.txt` files you're getting are probably the expected results.

As an extra note, for something like Decorative, you're probably going to need a lot of custom model definitions for the missing blocks - something the script can't do at the moment.

**Comment by bloxgate** [comment]
I've made some changes and I am now able to generate files for Architect's Palette and BattleTowers. I've updated the script and put the output for those two mods in the models folder. Let me know if you have any issues with slotlink.

**Comment by bloxgate** [comment]
I've uploaded a fix (2cda18e) for the issue you were seeing with BetterEnd.

**Comment by elhertz** [comment]
Thank you for fixing the bugs!
I don't feel comfortable sharing the files yet as I didn't test them thoroughly and also noticed errors in the console (probably because the name of some textures is not the same as the block name in-game)
I need to fix these errors and add the blocks that got left out and didn't get included in the file when using your tool.
Thanks!

**Comment by bloxgate** [comment]
I've pushed a fix for the issue with Go Fish as well. I'm going to go ahead and close this now.
